"""Normalized backend vocabulary for visual tags and synonym matching."""

from __future__ import annotations

TAG_CATEGORIES = (
    "palette",
    "lighting",
    "texture",
    "pattern",
    "silhouette",
    "material",
)

TAG_VOCABULARY: dict[str, dict[str, tuple[str, ...]]] = {
    "palette": {
        "warm neutrals": ("warm neutrals", "beige", "taupe", "warm beige"),
        "cool neutrals": ("cool neutrals", "grey", "gray", "stone", "cool beige"),
        "earth tones": ("earth tones", "brown", "olive", "terracotta", "earthy"),
        "pastels": ("pastels", "pastel", "soft pastel"),
        "jewel tones": ("jewel tones", "emerald", "sapphire", "ruby"),
        "monochromatic": ("monochromatic", "single-color", "single color"),
        "high contrast": ("high contrast", "strong contrast", "bold contrast"),
        "muted": ("muted", "subdued", "desaturated"),
        "vibrant": ("vibrant", "saturated", "bold color", "bright color"),
        "dark and moody": ("dark and moody", "moody palette", "deep palette"),
        "light and airy": ("light and airy", "airy palette", "bright white"),
        "black and white": ("black and white", "black-and-white", "monochrome"),
        "sage green": ("sage green", "sage"),
        "cream": ("cream", "ivory", "off-white", "off white"),
        "burgundy": ("burgundy", "wine red", "oxblood"),
    },
    "lighting": {
        "warm": ("warm light", "warm lighting", "golden light"),
        "cool": ("cool light", "cool lighting"),
        "natural": ("natural light", "daylight", "sunlight"),
        "soft": ("soft lighting", "soft light", "gentle light"),
        "harsh": ("harsh lighting", "hard light"),
        "golden hour": ("golden hour",),
        "dim": ("dim", "low light", "low-lit", "low lit"),
        "bright": ("bright", "well-lit", "well lit"),
        "moody": ("moody lighting", "moody", "dramatic lighting"),
        "ambient": ("ambient light", "ambient lighting"),
        "dramatic shadows": ("dramatic shadows", "heavy shadows", "strong shadows"),
        "diffused": ("diffused light", "diffuse light"),
        "candlelit": ("candlelit", "candle-lit", "candle light"),
        "neon": ("neon", "neon-lit", "neon lit"),
    },
    "texture": {
        "smooth": ("smooth", "sleek surface"),
        "rough": ("rough", "coarse"),
        "cozy": ("cozy", "comfortable", "inviting"),
        "sleek": ("sleek", "polished"),
        "layered": ("layered", "stacked styling", "layering"),
        "minimal": ("minimal", "pared back", "pared-back"),
        "rich": ("rich texture", "lush texture", "opulent"),
        "rustic": ("rustic", "weathered"),
        "polished": ("polished", "refined"),
        "distressed": ("distressed", "worn-in", "worn in"),
        "plush": ("plush", "soft pile", "velvety"),
        "woven": ("woven", "braided", "basket weave"),
        "knit": ("knit", "knitted"),
        "velvet": ("velvet", "velvety"),
        "leather": ("leather", "leathery"),
        "linen": ("linen",),
        "silk": ("silk", "silky"),
        "denim": ("denim", "jean material"),
    },
    "pattern": {
        "solid": ("solid", "plain"),
        "floral": ("floral", "flower print", "botanical"),
        "geometric": ("geometric", "angular pattern"),
        "stripes": ("stripes", "striped"),
        "plaid": ("plaid", "tartan"),
        "abstract": ("abstract",),
        "animal print": ("animal print", "leopard print", "zebra print"),
        "paisley": ("paisley",),
        "polka dots": ("polka dots", "polka dot"),
        "checkered": ("checkered", "checkerboard"),
        "toile": ("toile",),
        "damask": ("damask",),
        "tie-dye": ("tie-dye", "tie dye"),
        "camo": ("camo", "camouflage"),
        "houndstooth": ("houndstooth",),
    },
    "silhouette": {
        "oversized": ("oversized", "over-sized", "slouchy"),
        "fitted": ("fitted", "close-fitting", "tailored close"),
        "flowy": ("flowy", "flowing", "drapey"),
        "structured": ("structured", "architectural", "sharp lines"),
        "layered": ("layered look", "layered silhouette"),
        "streamlined": ("streamlined", "clean silhouette"),
        "a-line": ("a-line", "a line"),
        "boxy": ("boxy",),
        "asymmetric": ("asymmetric", "asymmetrical"),
        "relaxed": ("relaxed", "easy fit"),
        "tailored": ("tailored", "precise fit"),
        "cropped": ("cropped",),
        "elongated": ("elongated", "long line"),
        "voluminous": ("voluminous", "full shape"),
    },
    "material": {
        "wood": ("wood", "wooden"),
        "metal": ("metal", "metallic"),
        "glass": ("glass",),
        "ceramic": ("ceramic", "stoneware"),
        "fabric": ("fabric", "textile"),
        "leather": ("leather",),
        "rattan": ("rattan", "wicker", "cane"),
        "marble": ("marble",),
        "concrete": ("concrete", "cement"),
        "brass": ("brass",),
        "copper": ("copper",),
        "chrome": ("chrome", "chromed"),
        "natural fibers": ("natural fibers", "natural fibre", "cotton", "wool"),
        "synthetic": ("synthetic", "polyester", "nylon"),
    },
}

INFERRED_HINTS: tuple[tuple[str, str, str], ...] = (
    ("palette", "warm neutrals", "neutral palette"),
    ("palette", "earth tones", "earthy tones"),
    ("lighting", "natural", "sunlit"),
    ("lighting", "moody", "shadowy"),
    ("texture", "cozy", "homey"),
    ("texture", "minimal", "clean and uncluttered"),
    ("texture", "distressed", "worn"),
    ("pattern", "solid", "no visible pattern"),
    ("pattern", "floral", "flowers"),
    ("silhouette", "flowy", "draped"),
    ("silhouette", "structured", "clean lines"),
    ("silhouette", "relaxed", "loose fit"),
    ("material", "wood", "oak"),
    ("material", "metal", "steel"),
    ("material", "leather", "hide"),
    ("material", "natural fibers", "linen"),
)
